<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />
    <xacro:property name="forearm_radius" value="0.02" />
    <xacro:property name="forearm_length" value="0.3" />
    <xacro:property name="hand_radius" value="0.02" />
    <xacro:property name="hand_length" value="0.3" />

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 ${arm_base_height / 2.0}" rpy="0 0 0" />
            <material name= "orange">
                <color rgba= "1.0 0.5 0 1" />
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}" />
            </geometry>
            <origin xyz="0 0 ${arm_base_height / 2.0}" rpy="0 0 0" />
        </collision>
        <!-- <inertial>
            <origin xyz= "0 0 ${arm_base_height / 2.0}" rpy= "0 0 0"/>
            <mass value= "0.5" />
            <inertia ixx="${(0.5/12) * (arm_base_length * arm_base_length + arm_base_height * arm_base_height)}" ixy="0" ixz="0"
                     iyy = "${(0.5/12) * (arm_base_length * arm_base_length + arm_base_width * arm_base_width)}" iyz="0"  
                     izz="${(0.5/12) * (arm_base_height * arm_base_height + arm_base_width * arm_base_width)}" />
        </inertial> -->
        <xacro:box_inertia m="0.5" l="${arm_base_length}" w="${arm_base_width}" 
        h="${arm_base_height}" xyz="0 0 ${arm_base_height/2.0}" rpy="0 0 0"/>
    </link>


    <link name="forearm_link">
        <visual>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}" />
            </geometry>
            <origin xyz="0 0 ${forearm_length / 2.0}" rpy="0 0 0" />
            <material name="yellow" >
                <color rgba= "1.0 1.0 0 1" />
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${forearm_radius}" length="${forearm_length}" />
            </geometry>
            <origin xyz="0 0 ${forearm_length / 2.0}" rpy="0 0 0" />
        </collision>
        <!-- <inertial>
            <origin xyz= "0 0 ${forearm_length / 2.0}" rpy= "0 0 0"/>
            <mass value= "0.3" />
            <inertia ixx="${(0.3/12) * (3 * forearm_radius * forearm_radius + forearm_length * forearm_length)}" ixy="0" ixz="0"
                     iyy = "${(0.3/12) * (3 * forearm_radius * forearm_radius + forearm_length * forearm_length)}" iyz="0"  
                     izz="${(0.3/2) * (forearm_radius * forearm_radius)}" />
        </inertial> -->
        <xacro:solid-cylinder_inertia m= "0.3" r= "${forearm_radius}"  h="${forearm_length}"
                         xyz="0 0 ${forearm_length / 2.0}" rpy="0 0 0"/>
    </link>


    <link name="hand_link">
        <visual>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
            <material name="orange" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${hand_radius}" length="${hand_length}" />
            </geometry>
            <origin xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0" />
        </collision>
        <!-- <inertial>
            <origin xyz= "0 0 ${hand_length / 2.0}" rpy= "0 0 0"/>
            <mass value= "0.3" />
            <inertia ixx="${(0.3/12) * (3 * hand_radius * hand_radius + hand_length * hand_length)}" ixy="0" ixz="0"
                     iyy = "${(0.3/12) * (3 * hand_radius * hand_radius + hand_length * hand_length)}" iyz="0"  
                     izz="${(0.3/2) * (hand_radius * hand_radius)}" />
        </inertial> -->
        <xacro:solid-cylinder_inertia m= "0.3" r= "${hand_radius}"  h="${hand_length}"
            xyz="0 0 ${hand_length / 2.0}" rpy="0 0 0"/>
    </link>

    
    <joint name="arm_base_forearm_joint" type="revolute">
        <parent link="arm_base_link" />
        <child link="forearm_link" />
        <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi/2}" effort="100" velocity="100" />
        <dynamics friction="0.05" damping="0.1"/>
    </joint>

    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link" />
        <child link="hand_link" />
        <origin xyz="0 0 ${forearm_length}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
        <limit lower="0" upper="${pi/2}" effort="100" velocity="100" />
        <dynamics friction="0.05" damping="0.1"/>
    </joint>

    
    <gazebo reference="arm_base_link">
        <material>Gazebo/Orange</material>
    </gazebo>

    <gazebo reference="forearm_link">
        <material>Gazebo/Yellow</material>
    </gazebo>

    <gazebo reference="hand_link">
        <material>Gazebo/Orange</material>
    </gazebo>

</robot>
